// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAMJXEUXCk7kAT7SX_LjIn25_jZ4nJ2Hs',
    appId: '1:958920008500:android:dfe27508f87cf53a9ffb61',
    messagingSenderId: '1062914573378',
    projectId: 'privilee-test',
    storageBucket: 'privilee-test.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAMJXEUXCk7kAT7SX_LjIn25_jZ4nJ2Hs',
    appId: '1:958920008500:android:dfe27508f87cf53a9ffb61',
    messagingSenderId: '1062914573378',
    projectId: 'privilee-test',
    storageBucket: 'privilee-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAMJXEUXCk7kAT7SX_LjIn25_jZ4nJ2Hs',
    appId: '1:958920008500:android:dfe27508f87cf53a9ffb61',
    messagingSenderId: '1062914573378',
    projectId: 'privilee-test',
    storageBucket: 'privilee-test.appspot.com',
    iosClientId: '1062914573378-ft3n4akfg3uhq051067g4tj9pgodceb1.apps.googleusercontent.com',
    iosBundleId: 'ro.invictustech.privilee',
  );
}
